In [1]:
import numpy as np

In [4]:
a = [1,2,3,4]
b= np.array(a)
type(b)

numpy.ndarray

In [5]:
b.shape

(4,)

In [7]:
b.argmax()

3

In [8]:
b.max()


4

In [9]:
b.mean()

2.5

In [13]:
c =[[1,2],[3,4]]
d = np.array(c)

In [14]:
d.shape

(2, 2)

In [16]:
d.size

4

In [18]:
d.max(axis=0)


array([3, 4])

In [19]:
d.max(axis=1)

array([2, 4])

In [20]:
d.mean(axis=0)

array([2., 3.])

In [21]:
d.flatten()

array([1, 2, 3, 4])

In [22]:
np.ravel(c)

array([1, 2, 3, 4])

In [24]:
e = np.ones((3,3), dtype=np.float32)
print(e)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
g= np.zeros((2,2,3), dtype=np.float32)
print(g)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [28]:
#e为底的指数函数
print(np.exp(3))
#2的3次方
print(np.power(2,3))
#点积,1*3+2*4
print(np.dot([1,2],[3,4]))

#两个向量a = [a1, a2,…, an]和b = [b1, b2,…, bn]的点积定义为：
#a·b=a1b1+a2b2+……+anbn。
#使用矩阵乘法并把（纵列）向量当作n×1 矩阵，点积还可以写为：
#a·b=a^T*b，这里的a^T指示矩阵a的转置。

#https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

20.085536923187668
8
11
